{
 "title": "Catcher / Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(gin_gonic_requests_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "gin_gonic_requests_total{code=~\"5.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG response time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(gin_gonic_request_duration_bucket[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "100*(sum(rate(gin_gonic_requests_total{code=~\"5.*\"}[5m]))\n/ sum(rate(gin_gonic_requests_total[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count of events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "gin_gonic_request_duration_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(webhook_sender_request_duration_seconds_count)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(webhook_sender_request_duration_seconds_bucket{le=\"0.01\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}