{
 "title": "Events Performance",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "customer", "query": { "query": "label_values(customer_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Instance count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(count by(instance) (consumer_ingested_events_total))",
     "legendFormat": "Consumers "
    },
    {
     "expr": "count(count by(instance) (producer_enqueued_events_total))",
     "legendFormat": "Producers"
    },
    {
     "expr": "count(count by(thread_id, instance) (notifier_notification_lag_count))",
     "legendFormat": "Notifiers"
    },
    {
     "expr": "count(count by(instance) (catcher_received_events_total))",
     "legendFormat": "Catchers"
    }
   ]
  },
  {
   "title": "Total Rates ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(producer_enqueued_events_total{customer_id=~\"${customer}\"}[$__rate_interval]))",
     "legendFormat": "Enqueueing"
    },
    {
     "expr": "sum(rate(consumer_ingested_events_total{customer_id=~\"${customer}\"}[$__rate_interval]))",
     "legendFormat": "Ingestion"
    },
    {
     "expr": "sum(rate(catcher_received_events_total{customer_id=~\"${customer}\"}[$__rate_interval]))",
     "legendFormat": "Сaught"
    },
    {
     "expr": "sum(rate(notifier_posted_events_total{customer_id=~\"${customer}\"}[$__rate_interval]))",
     "legendFormat": "Delivered (Notifier)"
    },
    {
     "expr": "sum(rate(notifier_failed_events_total{customer_id=~\"${customer}\"}[$__rate_interval]))",
     "legendFormat": "Failed to Deliver (Notifier)"
    }
   ]
  },
  {
   "title": "Delivery Lag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (customer_id) (rate(notifier_delivery_lag_sum{customer_id=~\"${customer}\"}[$__rate_interval]) / rate(notifier_delivery_lag_count{customer_id=~\"${customer}\"}[$__rate_interval])) \n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notifier: AVG duration by customer",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(customer_id) (rate(notifier_request_duration_seconds_bucket{customer_id=~\"${customer}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification rates (notifier)",
   "type": "timeseries",
   "description": "Per customer, number of notifications delivered/processed by customer's notification callback(catcher)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(customer_id) (rate(notifier_posted_events_total{customer_id=~\"${customer}\"}[$__rate_interval]))",
     "legendFormat": "Delivered {{customer_id}}"
    },
    {
     "expr": "sum by(customer_id) (rate(notifier_retried_events_total{customer_id=~\"${customer}\"}[$__rate_interval]))",
     "legendFormat": "Failed to deliver {{customer_id}}"
    }
   ]
  },
  {
   "title": "Notifier: Errors Count",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (customer_id) (notifier_retried_events_total{customer_id=~\"${customer}\"})",
     "legendFormat": "{{customer_id}}"
    }
   ]
  },
  {
   "title": "Notifier AVG Errors by Code",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (customer_id) (rate(notifier_retried_events_total{customer_id=~\"${customer}\"}[$__rate_interval]))",
     "legendFormat": "{{customer_id}}"
    }
   ]
  },
  {
   "title": "Catcher received events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by(customer_id) (rate(catcher_received_events_total{customer_id=~\"${customer}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notifier: AVG duration with quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "quantile(0.95, avg(rate(notifier_request_duration_seconds_bucket{customer_id=~\"${customer}\"}[$__rate_interval])))",
     "legendFormat": "Quantile 95%"
    },
    {
     "expr": "quantile(0.5, avg(rate(notifier_request_duration_seconds_bucket{customer_id=~\"${customer}\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "Quantile 50%"
    },
    {
     "expr": "quantile(0.01, avg(rate(notifier_request_duration_seconds_bucket{customer_id=~\"${customer}\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "Quantile 1%"
    }
   ]
  },
  {
   "title": "Enqueuing rates (producer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(customer_id) (rate(producer_enqueued_events_total{customer_id=~\"${customer}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notifier: Error Statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "notifier_failed_events_total{customer_id=~\"${customer}\"}",
     "legendFormat": "Status: {{status}}   Customer: {{customer_id}}   Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Ingestion rates (consumer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum by(customer_id) (rate(consumer_ingested_events_total{customer_id=~\"${customer}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notifier Threads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (thread_id, instance) (notifier_thread_posted_events_total{customer_id=~\"${customer}\"})",
     "legendFormat": "{{instance}} - {{thread_id}}"
    },
    {
     "expr": "sum by (thread_id, instance) (notifier_thread_failed_events_total{customer_id=~\"${customer}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Posted / Deliveder by Customer",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (customer_id) (notifier_posted_events_total{customer_id=~\"${customer}\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (customer_id) (catcher_received_events_total{customer_id=~\"${customer}\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}