{
 "title": "Events Unaffected Performance",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "customer", "query": { "query": "label_values(customer_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Prove",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (mode) (100*1000*notifier_retried_events_total{customer_id=~\"${customer}\",mode=\"nightmare\"}/notifier_sent_events_total{customer_id=~\"${customer}\",mode=\"nightmare\"})",
     "legendFormat": "Nightmare: Fail Rate"
    },
    {
     "expr": "avg by (mode) (100*1000*notifier_retried_events_total{customer_id=~\"${customer}\",mode=\"hell\"}/notifier_sent_events_total{customer_id=~\"${customer}\",mode=\"hell\"})",
     "legendFormat": "Hell: Fail Rate"
    },
    {
     "expr": "avg by (mode) (rate(notifier_delivery_lag_sum{customer_id=~\"${customer}\",mode=\"nightmare\"}[$__rate_interval]) / rate(notifier_delivery_lag_count{customer_id=~\"${customer}\",mode=\"nightmare\"}[$__rate_interval])) ",
     "legendFormat": "Nightmare: Delivery Lag"
    },
    {
     "expr": "avg by (mode) (rate(notifier_delivery_lag_sum{customer_id=~\"${customer}\",mode=\"hell\"}[$__rate_interval]) / rate(notifier_delivery_lag_count{customer_id=~\"${customer}\",mode=\"hell\"}[$__rate_interval])) ",
     "legendFormat": "Hell: Delivery Lag"
    }
   ]
  },
  {
   "title": "Unaffected Performance: how to check",
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "#### Context:\n`Unaffected performance` - potential performance degradation of one or more notification handlers must not affect the performance of the rest notification handlers.\n\n#### Modes description:\n- `Nightmare` mode, which provides about 33% of probability of delay or exception (500 status code) will be returned.\n- `Hell` mode, which always returns an exception (500 status code).\n\n#### Start configuration:\n- two notification handlers with `nightmare` mode, a possible delay of 500-1000 ms, and status code 500, with a probability about 33% of one of the assaults will be executed.\n- one notification handler will be looped by two modes, starting with a `nightmare` - which will last 1 minute, switch to `hell` - which will last 3 minutes, and return to the nightmare again, so these modes will change each other and again and again.\n- one notification handler without any modes, so it will work without expected delays or exceptions.\n\n#### Prove:\n- on the `Prove` panel, you can see that `Hell: Delivery Lag` growing while we can't post the event, but after `hell` stopped, it disappeared, and `Hell: Fail Rate` grows a bit and then keep the same (we have looped modes which keep it almost the same), both factors means that `hell` stopped and other modes are not affected.\n- on one of `Number of delivered` panels, which is under `hell` mode, for some period of time, the count of delivered events remains unchanged.\n- on one of `Customer Delivered/Failed` panels, which is under `hell` mode, you can see 100% of failed-to-deliver attempts.\n- on one of `Customer Delivery Lag` panels, which is under `hell` mode, missed any values, which means that there are no delivered events and we can't calculate the lag.\n- on the `Total Rates` panel we can see that only for one customer the count of delivered events remains unchanged, others keep working and their count of delivered events is still rising.\n"
   }
  },
  {
   "title": "Customer: ${customer}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "repeat": "customer",
   "targets": [
    {
     "expr": "sum by (customer_id) (notifier_delivery_lag_count{customer_id=~\"${customer}\",mode=\"\"})",
     "legendFormat": "Number of delivered"
    }
   ]
  },
  {
   "title": "Customer: ${customer}",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 9 },
   "repeat": "customer",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (customer_id) (rate(notifier_delivery_lag_sum{customer_id=~\"${customer}\",mode=\"\"}[$__rate_interval]) / rate(notifier_delivery_lag_count{customer_id=~\"${customer}\",mode=\"\"}[$__rate_interval])) \n",
     "legendFormat": "Delivery Lag"
    }
   ]
  },
  {
   "title": "Customer: ${customer}",
   "type": "piechart",
   "description": "Per customer, number of notifications delivered/processed by customer's notification callback(catcher)",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "repeat": "customer",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(customer_id) (rate(notifier_posted_events_total{customer_id=~\"${customer}\"}[$__rate_interval]))",
     "legendFormat": "Delivered"
    },
    {
     "expr": "sum by(customer_id) (rate(notifier_retried_events_total{customer_id=~\"${customer}\"}[$__rate_interval]))",
     "legendFormat": "Failed to deliver"
    }
   ]
  },
  {
   "title": "Total Rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by (customer_id) (notifier_delivery_lag_count{customer_id=~\"${customer}\",mode=\"\"})",
     "legendFormat": "Delivered {{customer_id}}"
    },
    {
     "expr": "sum by (customer_id) (consumer_ingested_events_total{customer_id=~\"${customer}\"})",
     "legendFormat": "Ingested {{customer_id}}"
    }
   ]
  }
 ]
}